if: tag IS blank
branches:
  only:
  - master
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      env: DOCKER_IMAGE=ubuntu:16.04 SWIFT_SNAPSHOT=4.2.1
    - os: osx
      osx_image: xcode10.1
      sudo: required
      env: SWIFT_SNAPSHOT=4.2.1
before_install:
- git clone https://github.com/IBM-Swift/Package-Builder.git
script:
- "./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR"
env:
  global:
    secure: BsyI6NjIdMwsnEjqU8/nPxanJ46c9Aajfrv9r7lNqDL0Y7XcO/TxM4jM3hqAx7A1AhJhkYin3uxLhpT5mE3Ev7MLMtpjt1v1GKNosltP3KLLzSkA6a6dyYEP0IdXwQZycgp8nSUI1QY1kgXyERJuMw3yizgBATI9iU9MEXMm0G1ncQsgEh/FAsYHjf4D2xg/qjXZ+SexFUbjLP2UHjfKWn5xTny2k9xnqpjaD9UtPNXpxfP3cjyeI6NYFZa/tzMcwIFwteqp1kVkwjjOgPF1159S/FXKZE44CGuwu5ODJjX2QJa5Ugv6on43FD3xXWdFCcbKs0+J5/i+JKFj1H9SkIOYhmmKwtK9Na278AQQAVPCTSzHxNv+LzsepIZvyD1+oIX/1h+cJGjP4iRvF0aWW61ocHrEK6O05ryKBoolfeQI/ytkjD8Tf/lbrItEudfK7NvoTegp3vI9oci3EVrAkbLsTD/XKzSUzxfEoOY9+zAnNdcKngcTpW9ela6AU5SgNgNnqVbpzDWXE0iqu8C/KXCVL6W2qAiPH4TpxWeOw4RIP0XlbxObsnE9LZDzE2mPH7EOJ4RV7i5MFbPpp+kMzTFYgI8JMAs30fWjbrkURLm3rl4JKUFKTP96+++mF3CETLVvEtEvoZVdzXe3T9i6eN0HZKotVpwCIlwzc9Ois6g=
