# Only create a build job IF there is no tag in the commit
if: tag IS blank
# Only create a build job IF the branch is 'master'
branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9
      sudo: required

before_install:
  - git clone https://github.com/IBM-Swift/Package-Builder.git

script:
  - ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR

#env:
#  global:
#    - SWIFT_BRANCH=swift-4.2-branch
#    - SWIFT_VERSION=swift-4.2-DEVELOPMENT-SNAPSHOT-2018-05-30-a
#    - PACKAGE_VERSION=0.0.1
#
#jobs:
#  include:
#    - OSX test
#
#os: osx
#osx_image: xcode10.1
#language: swift
#sudo: required
#
#install:
#  - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
#  - wget https://swift.org/builds/$SWIFT_BRANCH/xcode/$SWIFT_VERSION/$SWIFT_VERSION-osx.pkg
#  - sudo installer -pkg $SWIFT_VERSION-osx.pkg -target /
#  - export PATH="/Library/Developer/Toolchains/$SWIFT_VERSION.xctoolchain/usr/bin:$PATH"
#
#script:
#  - swift package update
#  - swift test
#  stage: Set tag
#
